### ISSUE TITLE
Easiest way for people to specify what they want served up

### ISSUE THREAD

**Issue by ZavixDragon** [ZavixDragon/LiteJavaWebsite#1]
Should they specify a list of files to load based on the uri passed in.

or should I automatically load the html, js, css under the same name as the uri entered

or I could do both that the override the default resource map and pass in their own when they want to load up multiple files

**Comment by SilasReinagel** [comment]
This issue doesn't have quite enough context.

Are you asking whether an explicit list of files should be served, instead of pulling all of "site" by convention?

If so, it seems that a by-convention approach would work best.

**Comment by SilasReinagel** [comment]
Conventionally, the "index.html" page is loaded at any given path.

So, when a user browses to "www.site.com/help" then the browser would attempt to load "www.site.com/help/index.html".
